apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: base
  namespace: istio-system
  releaseName: istio-base
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.26.0
  includeCRDs: true
  valuesInline:
    defaultRevision: default
- name: istiod
  namespace: istio-system
  releaseName: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.26.0
  valuesInline:
    pilot:
      configMap: false
- name: gateway
  namespace: istio-system
  releaseName: istio-gateway
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.26.0
  valuesInline:
    service:
      type: ClusterIP
